name: kana_bus_app
description: "Get on the Bus and lets learn some Kana."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  email_validator: ^3.0.0
  equatable: ^2.0.7
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_pw_validator: ^1.6.0
  go_router: ^16.2.0
  google_sign_in: ^7.1.1
  hydrated_bloc: ^10.1.1
  logger: ^2.6.1
  kana_kit: ^2.1.1
  translator: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
