// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR6EWvHyYYS1l2KFhuON1bni8rdh14e9k',
    appId: '1:505721760943:android:d4ddc6be4d1486ef0eb85a',
    messagingSenderId: '505721760943',
    projectId: 'the-kana-bus',
    databaseURL: 'https://the-kana-bus-default-rtdb.firebaseio.com',
    storageBucket: 'the-kana-bus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtAZnoJOutjK8qRwkyYq8EbN84SDB40Lc',
    appId: '1:505721760943:ios:c6e49a3a711c37b50eb85a',
    messagingSenderId: '505721760943',
    projectId: 'the-kana-bus',
    databaseURL: 'https://the-kana-bus-default-rtdb.firebaseio.com',
    storageBucket: 'the-kana-bus.firebasestorage.app',
    iosClientId: '505721760943-3uqnou5ne9mssf3vqqgq8rcvnkt2o025.apps.googleusercontent.com',
    iosBundleId: 'com.dtfun.kanaBus',
  );
}
